apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: api-demo-m2-teste
  description: "api-demo-m2-teste"
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: "api-demo-m2-teste"
    github.com/project-slug: veecode-platform/api-demo-m2-teste
    vault.io/secrets-path: "api-demo-m2-teste"
    grafana/tag-selector: "api-demo-m2-teste"
    grafana/alert-label-selector: "alertname=api-demo-m2-teste"
    argocd/proxy-url: '/argocd/api'
    argocd/app-name: "api-demo-m2-teste"
spec:
  type: service
  lifecycle: experimental
  owner: admin



