apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-demo-m2-teste 
spec:
  selector:
    matchLabels:
      app: api-demo-m2-teste
  template:
    metadata:
      labels:
        app: api-demo-m2-teste
    spec:
      containers:
        - image: okteto.dev/java-gradle-api-demo-m2-teste:1.0.0
          name: api-demo-m2-teste

---

apiVersion: v1
kind: Service
metadata:
  name: api-demo-m2-teste
spec:
  type: ClusterIP
  ports:
    - name: "api-demo-m2-teste"
      port: 8080
  selector:
    app: api-demo-m2-teste

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-demo-m2-teste
  annotations:
    dev.okteto.com/generate-host: api-demo-m2-teste
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: api-demo-m2-teste
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific